/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MenuItem, Order, SavedLocation, UserProfile } from './types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // --- Starters ---
  {
    id: 'starter-1',
    name: 'Galouti Kebab',
    category: 'Starters',
    price: 850,
    rating: 4.9,
    description: 'Melt-in-mouth lamb kebabs, aromatic spices, served with mini ulte tawa paratha.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ugsXj-3f4wVAI-jmDTNv4oPXKz_YYUKpr4zqqRU-hyNvRqHKjhzp-tLSVGI2-_lJS8u9d_80piEq9G5izyrD6uT7Eh1MMBLWMiYO1Zg12yrQYy1Oiu4sYjh5vRH9yuyEQ_IO5iK4BlyIGB3Wh6ZsYceT-Z7dVxhd9Flwnur3GGxU3kJ5O77c11qknoMsshOXjPKZbomIA34FbP44K0zUhYtZijcMJn3UanmRqMGN6qRZbUP9QDmqwH1Mps',
  },
  {
    id: 'starter-2',
    name: 'Tandoori Lamb Rack',
    category: 'Starters',
    price: 1200,
    rating: 4.8,
    description: 'Perfectly charred lamb rack, mint chutney, pomegranate seeds.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ui8Th4-At3RTGdPJLvqzlL2npudY8a9xGlxNT03WmDuhXhKlGAis2426pzsljeQJ-fLSuUji8n_SgUvfdi8ycg2KRc-eHIRKRmr8ss0zDacawVG7XeIjPBW0UTAeZgJJEkj2O6f2wyiZSzlnvQRxVPdnp7aHVr9OGQ0TwViVCbpwc1KAZmHGepJMrSeVRkjrVieqgkS7_bizg1Phm44ruRIotSna2j_zob20sWmzeaINmk4OdHT2EYxLJk',
  },
  {
    id: 'starter-3',
    name: 'Peri-Peri Wings',
    category: 'Starters',
    price: 650,
    rating: 4.7,
    description: 'Charred texture, glistening glaze, served with a creamy dip.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ugeeKpR-nJ3UR5qGqjGVK92RYDBxnHa7RmdqtBVfDfSAoG4EbSv9cMw2KGg0YX1mR3TmmNla_09F3V7KryxqK_mx848uQHCyo6GdIJvBTNIs6ymobKyvSdENSVti0KyzpJzaL28xC8XsWgPHutwDJJF4gnZs886iCpurSt_UrDoaDSZu3fE9y6MJFIL9i8khZm3Dk4te1sPcji2AwRXwtZFLGzk5RBlV-LTo3VwhpLNaqt66XxHf8INkI0',
    spiceLevel: 'Medium',
    spicyCount: 3,
  },
  {
    id: 'starter-4',
    name: 'Mushroom Croquettes',
    category: 'Starters',
    price: 700,
    rating: 4.6,
    description: 'Crispy exterior, wild mushroom and truffle filling.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvjUQnz8oxS_IedBPkxX4Yh-m8ZPFMX1CI1VUY3iOaoZa3hwQTDkF_qoJWTEQwrEhHJy3B9oJ1W_-CY0Ky8KEXCFcRrULCwj6BN7Z9jCEBUa-OyvP6tgHRAX6ylvr_NGTXjfP47Yboob89p-YJYNKPtV4_2XaeVALVHGK0CcRaoSCJTeGEVWfd9sYynTwwb2_c_Ari6AF60qXx06akpY6OnOG0nfzbcigdS69Owx9eELVQiUGmtXfw95O5mluzrP7ig02fJHB2Pws',
  },
  {
    id: 'starter-5',
    name: 'Prawn Koliwada',
    category: 'Starters',
    price: 950,
    rating: 4.5,
    description: 'Spicy batter-fried prawns with curry leaves.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrCGDvgasH4_UGx22ka4ex3lccjfLqX3IgwCfugG0NguX_OcLLWP77G5_U_vigtOg1jovDN4Hd3wfH2--TCFoImvmPa-Xg5SMKIC9ZbQO2l4BYPD3nCKJwcwvpQGDdyEYYZMpxrwpuDk3SPFX8l-F-gpNV2doQY0MOLanvU2Rr6Nwl8bwgpPL59XzXWzXqo30Ig6hSwYiSS44doYXSeLfzhg9cVi57EogcboFJK7PpsaaZbCOx4vkh66DfiBQd57VOYHrEnLFPISY',
    spiceLevel: 'Mild',
    spicyCount: 1,
  },
  {
    id: 'starter-6',
    name: 'Charred Octopus',
    category: 'Starters',
    price: 1100,
    rating: 4.8,
    description: 'Tender tentacle, smoked paprika, lemon drizzle.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKTpDw2aWJbUOQm-UgcDXnP_MsCj9TYPINfjHa428pKjja3I1ZAUvu2hveLepxdY_31Zew0gpkIg6AT12v8ZKds3g0W2riqb4ppHOdcHkYwOtPh84xI7pNzwUKI467eLUxnjPCrazcgb2m0WTtVfJG3JoGkmx5yIkaBDIvlHVE7mm-EZL5Vnsstaw_EH2cZeRTorKP9Gy1FkMFTXQVcIounV4JSs1bBdmFmVMugYXlp1l2aqYQIgBUeLnnstDSoG33mmZiD_zWi-Y',
  },

  // --- Signature Mains ---
  {
    id: 'main-1',
    name: 'Mutton Rogan Josh',
    category: 'Signature Mains',
    price: 1450,
    rating: 4.9,
    description: 'Slow-cooked to perfection over 12 hours, our signature Rogan Josh features tender, prime cuts of mutton infused with a bespoke blend of Kashmiri spices. The resulting mahogany gravy is rich, aromatic, and layered with deep, complex flavors, finished with a subtle hint of saffron and toasted fennel.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhowfnyesTeh4ntP9RQVzXloO6CxHzYN5OhrQ7aCQgGb3xgkcCBeShRXzYJIlB_imAlG3QQh2DmNF7sYDEXM_9gIjBiYgko6WEC9k_zMLtRuPIAEHz-5ljoHOmkioIpstVdlTGcS-lmbqwqrNFWzAY-NTVfYoUDJq9qMXDvYLp5gW0kFK63SQfGWmnlj-BEvJ2bQpc9ecM7WKujgWLPvs2MaYS-TH8zmx_w9BsSujaVz7wDtbm6Y-lqjP8',
    spiceLevel: 'Medium',
    spicyCount: 2,
  },
  {
    id: 'main-2',
    name: 'Butter Chicken Pot Pie',
    category: 'Signature Mains',
    price: 1250,
    rating: 4.7,
    description: 'Flaky golden crust, rich tomato gravy with tender chicken thighs.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ui97OATS9ZMAsCRa6OZoue8i9frfHv3dQYM4AefrUbP0PvnZknNgQA4nDtX4zzG2kBurFdXu_BcGkqElo2XJTViApZmOTfE3mj2XN_EFshMFO-WM8ZEJiifcFRcQT5r3g9QMyVl2fpYoUXNHFyhuQVVMa02_1x3QneHR-_PuKlT0lwyJS_oHaHgIofOXQgw2qnTFTUPD6Ahk0wite9FN39FW7uFqs623BIIQRhqJE3XLPEslmoDrCEpBA0',
  },
  {
    id: 'main-3',
    name: 'Duck Confit',
    category: 'Signature Mains',
    price: 1800,
    rating: 4.8,
    description: 'Cherry reduction, parsnip puree, crispy skin.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uiEHukwfEfUmGnQiyRhRla-euUC4DI5ZJuorJ_I7nSSYLjG5j7awE3YCXVoAkb5n2NaBnklTDKwhqpZIHX4rZ4MTb-gF78ndH4imAoAYZBjUUyzfIpNdQOu1OvkWhMUOoxlFYDVxhNh84dyUoGditdlGuOClnSokzUROpgrqHqfTdEGEzC4f40xSxph2a5cp8nrTXS2Y0EDwV1FBENbc5UeZm1U1EtzClyah-WoAcYZXNblGA-LFhujkbI',
  },
  {
    id: 'main-4',
    name: 'Wagyu Burger',
    category: 'Signature Mains',
    price: 2200,
    rating: 4.9,
    description: 'Premium A5 wagyu patty, truffle aioli, gold leaf garnish, served with hand-cut fries.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0ujqMzyP563R3peK07jU4quQdWo1VSCWTdeoolbH4ZGO9CRL3d_BbzeiE4VS7nPFHZsqmH0-uYW9KHDMlfDrWo-aexpPDMh8Pp686gH31MfuH9rqLXaX-BRpYSHue-4glP-e884ngsw_k8jy2fY571wgCIUyw4xMSOI86F2j-D2tQuEVTSur9oQXXyAtiVenUECo4CvbPlZ9cvZcREnA2BliJOcf5mbcYO-qv9G3IZEZzNOzY3z2W6gy1eI',
  },
  {
    id: 'main-5',
    name: 'Nalli Nihari',
    category: 'Signature Mains',
    price: 1600,
    rating: 4.8,
    description: 'Slow-cooked lamb shanks in a rich, velvety, spicy bone marrow gravy with ginger filaments.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQWl4-j23fjGY9JBWVqErk2eIKcHJaDWyarGvSjTgdm16igfRzcML0ZxSS4-pbPoZpDfGvjlltRIGt4s47UUGqqdsSPEk4UOKM23wvM3dtho5D_dXAcD5qAFH82yBmVjqMFHO1FnvqjoJkCmlQ0l2c7DT8QxoRcHDxMcs1h7fq1vSl6in3I_Z3xC-nzBQ4rggScdq9H6YFDBlQmO61dEpDXtqz3-h22Ev_6zE7e5slVHukQiETgXgq0QJyEKjJ3Sj4O55qKckUXcU',
    spiceLevel: 'Medium',
    spicyCount: 2,
  },
  {
    id: 'main-6',
    name: 'Black Truffle Risotto',
    category: 'Signature Mains',
    price: 1900,
    rating: 4.7,
    description: 'Creamy French style risotto, Gruyère crust, shaved black summer truffle.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZWcTqeNvB-irDq84ct9fFRqkqNjZEmJVZ9dtS8czHDPLkZgWP9DRLe9ac0gBsSOOq1is3NDBCJM05sZ6BX_ioZWI0lICzWGINb3xHrBDx2XDlT3Jal3lz7vFPbeVQMo9x9PaTo5Q11uWAPfe7QHviuSmQQQOG7-2vR9xnFiVbeV902QVK-CLWvq5NznRov6_dysAhHR0MhNUMSduQmVSrezResZ-UsN6bQh-1fWZ1MNCMAiXqoxanUqQrk4QHWhfOFA-wdOujGiY',
  },

  // --- Coastal Seafood ---
  {
    id: 'seafood-1',
    name: 'Seafood Biryani',
    category: 'Coastal Seafood',
    price: 1850,
    rating: 4.7,
    description: 'Large premium platter with prawns and catch-of-the-day fish, long grain aged basmati rice, pristine saffron threads, served in a traditional handi.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhPqaHRR54xuHWew8eA1KRVVQ3iFBH14xhCKFfXaXpMZ6se1s2t_rowaeTQpX77psJWiiEK9dXtgY9MAklXAhd1wkdSl39Hrwk2NymPAE1aHje-LW7_eXSalLLbu7p_hmc2GVbdKF3Uwb6bzG0oPOf5KjgbFdgJYVVnqN5MUDUJQa0q6ytGK_gTq0_XkPmRv6vqegi-sOVNo6c62hAjM1UVS1C5Y_w-N9D4kcOzlCNpU50cQcBpj1x5uQA',
    spiceLevel: 'Mild',
    spicyCount: 1,
  },
  {
    id: 'seafood-2',
    name: 'Grilled Jumbo Prawns',
    category: 'Coastal Seafood',
    price: 2100,
    rating: 4.8,
    description: 'Tender jumbo prawns glazed with garlic butter, garden herbs, glistening shells.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhik_puJc31ReLGOOd_gpu4s7aaXfIG6TM1FK0qUOpCSFx4x46vhI4sW9phb2au8Ue2ltl02XeGpW8Qu1pEuYibkVDiOkbzkfVOo5q40HoM0h5ToKVJLNAhTUt6H2_u6FuDUqALxfexg8may6cxSmVfm3lzNxxXYDQmLnbshlsCppoD9MEYDFRue-okztI9PHTl2X4VSF1Y_cbC5YEzPsloeL8HxYTj5_ho2piJkSSmnH4eQGI0njbiOQc',
  },
  {
    id: 'seafood-3',
    name: 'Lobster Thermidor',
    category: 'Coastal Seafood',
    price: 3500,
    rating: 4.9,
    description: 'Luxurious French preparation served with sweet bay scallops and delicate saffron cream.',
    image: 'https://lh3.googleusercontent.com/aida/ADBb0uhLFy0ikEsQrmAcFtTrK1I0Dd1_L_3oFLm_uUHkdlW4EQmsAXQOdLtC4c-ngAKwZT1MDJ0pCW0bRU5XEML7dMAYO-GX0iFGdt-xGFSG6bT0dziWDYWNsDa816WJEXGdfSwyvC2JMqpRmXE1l5lI2JF8mY-kqZ89X2X_axFArlqQGvZyKxbed_FbZJVB26uUV3xxJ5En_25kNKr63T1DSb0yhGdqzpmVCl2YgeJxze2qRee5xBPARt05kdc',
  },
  {
    id: 'seafood-4',
    name: 'Malabar Fish Curry',
    category: 'Coastal Seafood',
    price: 1300,
    rating: 4.6,
    description: 'Traditional Kerala-style coconut milk broth, kokum, fresh catch of the day, mustard seeds.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCWY4PwHj24k-Se2ZTMG7Tk_L_-aIN_XtlYWH0hwsHP3qnW6wlLY0aeS-H7DOicA9ILoHH8RxeIELVm5dV4qvWcgyApP2M420wNlHMLH23DOHGxK9_JkiG2_uYLCMDtB-MwwZpUNmyaaWfMs8Jweu-Ljs8A7QVk2qytMGsul1WbkzZphrWJ_w5cOqMilVVyl0O0kyHROR-EXJ4Z98ECZx1HCLqQ_A9kE9AQNftYEgaDkCdKWZ4i3wOgDQwzOBuBFq4wJnMXq8GwvIc',
  },
  {
    id: 'seafood-5',
    name: 'Pan-Seared Scallops',
    category: 'Coastal Seafood',
    price: 1750,
    rating: 4.8,
    description: 'Hokkaido sea scallops, sweet pea purée, crispy pancetta dust.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD-TBsM9MXA3HkywDzdeIKupD-gAWwWHu1QgzeRngDeS_16zjBZF72MAbcT__6K_EkYaokJMsUwskTmqKKT-ES5MXp41j75X0w_kNvZ_DlNEbnkcviNYWvmyoyk255veWI21rFqBqEFn5dCVIkQCW-5w5RlPmdu2_ljUHJbwXnkJ5TrpOne4j4-lky7XdvnZDBxIaM-sgrO7r0con2D0_rhGf9nF5DOSJw9w2PT0GAHy35j8XvqeVY5GW4utKGR5fBygp4isgFvtpo',
  },
  {
    id: 'seafood-6',
    name: 'Goan Crab Masala',
    category: 'Coastal Seafood',
    price: 2400,
    rating: 4.7,
    description: 'Whole fresh mud crab cooked in a fiery roasted coconut and hand-ground chili gravy.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOfzD4ffm7GyYJgXX380uCV9TXR2j8t9qNcV6rsiYPhx3xcBA8xebnGPV9HreM8_0IlEipcYULuCA4DOURZO89_tgMKZzqTqtwV1z5-P-d7FmaLiNZuuXp6ArhDa_4XDZ8-yD1Tb9PXfkMeRzgr8kQNiAL130rGpBWAYh-K_pWUpOcEOqc3ThTMDBvghdeAZ6J5FIUc770UKNRo9ePaJtCXw2-w2rt1ji_1m1rA-IsChtK3-plLjyJn18F1Y3JKctN_9bLSlaAD1U',
    spiceLevel: 'Extra Spicy',
    spicyCount: 3,
  },

  // --- Desserts ---
  {
    id: 'dessert-1',
    name: 'Saffron Rasmalai',
    category: 'Desserts',
    price: 600,
    rating: 4.9,
    description: 'Delicate hand-rolled cottage cheese dumplings poached in cardamom-infused saffron milk, premium raw pistachio garnish.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCkVRbe1MYZlC586tEt90wngsbvMIZ80RAz256QL6okuxHO1nUvQJ0didYmYzJZp1ExWfcwO6mjwH7pFt1rFxzwNs9JEj257hbqyp_Hsh7fT_yhn2KEi93luqIqugLKKTd1bXmmA8_zrTAVo9XRptRnmpPsvb3HoGEvxZMkQYhtCS5Vr-Gfa2lO0u9vO-zt8CipblQ0057k7RvOXzw9CpKEuKT_Q1V_fXRmS3BOhryJ2OIgqmSWmLf6ASxYZsyKQobk-_rwO_NQhmk',
  },
  {
    id: 'dessert-2',
    name: 'Chocolate Fondant',
    category: 'Desserts',
    price: 750,
    rating: 4.8,
    description: 'Rich dark chocolate cake with a molten, gooey center, served alongside a scoop of Madagascar vanilla bean ice cream.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0w7TjppDJwyr4ms-JYYgbTmh5H6VZcjIMuvbc-rPEWaiZqDodd93_csajTTBbVU-WVjhCzFZuLZjadzpth9VOfUTxBsm4_PoYwsrO-B8BxIL_qDq_tYLxVQ_j7N8YT9wbuH0NKap4rxUQdsV8oWV21Vyl6gRLCLfezp2YsC3hgm03PDj2HcKJYHY-gZLxnKAcDp-VZMCaSNbuOY90ZKblyHetgRJ7OkDdy3bpzgA48IXVjV9sZ-eTSCyLUwEv8I_qJe8Yv7VJa1o',
  },
  {
    id: 'dessert-3',
    name: 'Pistachio Baklava',
    category: 'Desserts',
    price: 800,
    rating: 4.8,
    description: 'Flaky layers of pristine crispy phyllo dough, organic floral wild honey syrup, crushed premium Turkish pistachios.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBDUL965aXuU3YWP3hqcMhdd-pHAVJbPy5qiN3OdRBChOmxn1HoVgyYS22LIZQQxUE0Wc45SfVfGatpPtZA7Ck-rWllhTj8dFfElFSa0ASo6pAqElf2Z9l2SiVCh5J1o122MqknrZlPVzI8iqgQxDblyoblHWNozpQYQ5960e6-eN1rTQWuYXkW0o1d81iRBKDVG0sHIf2IPPgsWd1xwj94-wNZS2FVVAU3vyMxKd3dRmROkY4VFHARQrHsfNLnVInA5fkleveIljk',
  },
  {
    id: 'dessert-4',
    name: 'Tiramisu',
    category: 'Desserts',
    price: 650,
    rating: 4.7,
    description: 'Classic Italian pick-me-up with espresso soaked ladyfingers and whipped egg-yolk-rich mascarpone cream.',
    icon: 'cake',
  },
  {
    id: 'dessert-5',
    name: 'Artisanal Gelato',
    category: 'Desserts',
    price: 500,
    rating: 4.6,
    description: 'A custom daily selection of three house-made premium dense gelato flavors (Pistachio, Dark Chocolate, Salted Caramel).',
    icon: 'icecream',
  },
  {
    id: 'dessert-6',
    name: 'Crème Brûlée',
    category: 'Desserts',
    price: 700,
    rating: 4.7,
    description: 'Rich, smooth custard base flavored with authentic vanilla bean and topped with a glass-like caramelized sugar crust.',
    icon: 'local_cafe',
  },
  {
    id: 'dessert-7',
    name: 'Fruit Tart',
    category: 'Desserts',
    price: 550,
    rating: 4.5,
    description: 'Crisp, sweet, buttery shell filled with luscious pastry cream and adorned with seasonal organic raspberries and glaze.',
    icon: 'bakery_dining',
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Alexander Sterling',
  email: 'a.sterling@example.com',
  phone: '+1 (555) 019-8372',
  isBlackCard: true,
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'LM-8924',
    items: [
      {
        name: 'Japanese A5 Wagyu Ribeye & Truffle Butter',
        quantity: 1,
        price: 245.00,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCewh3rkwbpYRM0Vilyros2-VgQl4YIBY5VDwmj3NWcgegY_VPDMRCrqOajm2paad1XlgHL0EdjigIaGk2CKOVFdRQrYdVY8afJkmf_cPW2vaGE61xxfndUvapK_OT5R29unFlz4RcKO8OAQLfbTD_Hz15UzYd_4ndgOFD5lIjbpCVGkBc6hi6QAgdR65e7r7m2yLTqj92oL-8SnpNqtRioWs2H8yp845uu9lJ__Ej_9sEK7vOkWTRp6zPM2tkXOpfN3qrmYFGHic',
      }
    ],
    subtotal: 245.00,
    tax: 19.60,
    deliveryFee: 15.00,
    total: 279.60,
    date: 'Oct 24, 2024',
    status: 'Shipped',
  },
  {
    id: 'LM-8851',
    items: [
      {
        name: 'Dry-Aged Tomahawk (32oz)',
        quantity: 1,
        price: 180.00,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5tl_7H5uvJCohf4l-3pl5TwmRCP0HdnaSChHeNRAVVJ5s6kdvjWm2SwkWqIA7spzA3h1hqf7zLN6ujFN64HG5miXuphlDqRRAqUcT4B_D8_QcnR15RCBtDBmIhTFuPQgoihkyZaaWdaaLCeV1dMt5D0FWGtBLhIsrruQxbyyQUjKb1j8Ze6R7Y7fk5zeOHWX_bIo-_JVJZtdIvSKxl79Cucysp6F2yT61H6mATFeV85SchEHY7BikOL6HmdBo77ABlnhUq8U3l7E',
      }
    ],
    subtotal: 180.00,
    tax: 14.40,
    deliveryFee: 15.00,
    total: 209.40,
    date: 'Sep 12, 2024',
    status: 'Delivered',
  },
];

export const INITIAL_SAVED_LOCATIONS: SavedLocation[] = [
  {
    id: 'loc-1',
    label: 'PRIMARY RESIDENCE',
    address: '1745 Luxury Lane, Suite 400',
    city: 'Beverly Hills, CA',
    postalCode: '90210',
    instructions: 'Delivery Instructions: Leave with concierge.',
  },
  {
    id: 'loc-2',
    label: 'OFFICE',
    address: '500 Corporate Blvd, Floor 12',
    city: 'Los Angeles, CA',
    postalCode: '90014',
    instructions: 'Delivery Instructions: Front reception.',
  },
];
